### ISSUE TITLE
Make DNS pod resilient

### ISSUE THREAD

**Issue by aku105** [DigitalInnovation/acs-engine#7]
**Is this a request for help?**:
No

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
FEATURE

---

**What version of acs-engine?**:
Latest

---

DNS pod should be made more resilient since it's one of the important services in cluster on which any pod depends, if they need to communicate with other services inside or outside of cluster. Some possible improvements:
1. Run DNS pods as Deployment and have a Kubernetes service on top of the pods.
2. Configure an autoscaler on DNS pods, so that deployment can scale up under load.
3. Use `addonmanager.kubernetes.io/mode: Reconcile` to allow addon manager to keep the service up.
4. Make the DNS pods' QOS guaranteed.
5. Increase verbosity of `dnsmasq` and ship the logs to stderr for analysis.

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
N/A

**What you expected to happen**:
N/A

**How to reproduce it** (as minimally and precisely as possible):
N/A

**Anything else we need to know**:
N/A

**Comment by yfernando** [comment]
This issue is ok to be raised in upstream repo and raise the PR against it.
