### ISSUE TITLE
ACS-Engine CIS compliance issue

### ISSUE THREAD

**Issue by kajanth** [DigitalInnovation/acs-engine#8]
**Is this a request for help?**:  
No

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
FEATURE

---

**What version of acs-engine?**:
Latest

---

The configuration of the ACS-Engine Kubernetes cluster and it's components does not confirm to CIS benchmarking standards 1.8

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
There are a high number of failures reported.

**What you expected to happen**:
N/A

**How to reproduce it** (as minimally and precisely as possible):
This article has the information on how to run the bench mark https://github.com/nccgroup/kube-auto-analyzer

**Anything else we need to know**:
N/A

**Comment by aku105** [comment]
>There are a high number of failures reported.

We should add that there are many critical failures reported as well, to show the risk.

> it's components does not *confirm* to CIS benchmark

Typo: conform

We were talking about attaching a nondescript report as well. Are we just going to give the link to generate report automatically?

**Comment by aku105** [comment]
Also, I think this should be raised as an `issue` instead of `feature`

**Comment by yfernando** [comment]
Attach the os benchmark report and raise this in upstream repo.
